[package]
name = "is_openable_pdf"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.100"
lopdf = { version = "0.36.0", default-features = false }
getrandom = { version = "0.3.3", default-features = false, features = [
  "wasm_js",
] }
